# Generated by Django 6.1 on 2026-08-25 21:36

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_alter_question_enonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ordre_dans_groupe',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type_question',
            field=models.CharField(choices=[('QCM', 'Choix multiple'), ('LIBRE', 'Réponse libre'), ('COURTE', 'Réponse courte')], default='QCM', max_length=10),
        ),
        migrations.CreateModel(
            name='ExerciceGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enonce_principal', django_ckeditor_5.fields.CKEditor5Field()),
                ('ordre', models.PositiveSmallIntegerField()),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices_groupes', to='evaluations.examen')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapes', to='evaluations.exercicegroupe'),
        ),
    ]
