# Generated by Django 6.1

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0006_question_ordre_dans_groupe_and_more'),
        ('pedagogie', '0001_initial'),
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueProgression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_maitrise', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_snapshot', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_progressions', to='comptes.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogie.matiere')),
            ],
            options={
                'ordering': ['date_snapshot'],
            },
        ),
    ]
