# Generated by Django 6.1 on 2026-08-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0007_historiqueprogression"),
    ]

    operations = [
        migrations.AddField(
            model_name="examen",
            name="editeur_math",
            field=models.CharField(
                choices=[
                    ("HERITER", "Hériter de la matière"),
                    ("ACTIF", "Actif"),
                    ("INACTIF", "Inactif"),
                ],
                default="HERITER",
                help_text="Contrôle l'affichage de la barre d'outils mathématiques (KaTeX) pour cet examen.",
                max_length=10,
            ),
        ),
    ]
