# Generated by Django 6.1 on 2026-08-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communaute', '0006_ajout_lu_messageprive'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageprive',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='devoirs/'),
        ),
        migrations.AlterField(
            model_name='messageprive',
            name='contenu',
            field=models.TextField(blank=True, default=''),
        ),
    ]
