# Generated by Django 6.1 on 2026-08-25 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_initial'),
        ('pedagogie', '0005_alter_sequence_contenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursProgression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='pedagogie.cours')),
                ('derniere_sequence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedagogie.sequence')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions_cours', to='comptes.eleve')),
            ],
            options={
                'unique_together': {('eleve', 'cours')},
            },
        ),
    ]
