# Generated by Django 6.1 on 2026-08-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedagogie", "0006_coursprogression"),
    ]

    operations = [
        migrations.AddField(
            model_name="matiere",
            name="editeur_math_actif",
            field=models.BooleanField(
                default=False,
                help_text="Activer l'éditeur mathématique (KaTeX) par défaut pour les examens de cette matière.",
            ),
        ),
    ]
